.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "FOO" "1" "December 2010" "" ""
.
.SH "NAME"
\fBfoo\fR \-\- do some foo
.
.SH "SYNOPSIS"
.
.nf
foo [\-v] [\-h]
.
.fi
.
.SH "DESCRIPTION"
Do some foo!
.
.SH "OPTIONS"
The following options are supported:
.
.P
\-v
.
.IP "" 4
.
.nf
Verbose\.

Or should this be a version option?
.
.fi
.
.IP "" 0
.
.P
\-h
.
.IP "" 4
.
.nf
Help output\.

Perhaps I should add \'\-\-help\' too\.
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
.
.nf
bar(1)
.
.fi

